- .github/helm-docs.sh
- .github/kubeval.sh
- .github/workflows/ci.yaml
k8s 0.12.x and 0.13.x have now been dropped by AWS, Azure, and GCP
> ci: drop deprecated k8s

- .github/ct.yaml
- .github/workflows/ci.yaml
- charts/renovate/Chart.yaml
- charts/renovate/README.md
* fix readme
* diable version lint (no version change would be a noop, so changes would be published by next bump)
ref #52 #54 #55
> fix: wrong readme

- .github/kubeval.sh
- charts/renovate/Chart.yaml
- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Existing "secrets" property provides a limited and unsecure way to pass sensitive values to the cron job.
Proposed change allows a user to provide arbitrary secrets\configmaps that are injected as environment variables into the pod.
> Propagate "envFrom" property to CronJob

- .github/helm-docs.sh
- .github/kubeval.sh
- charts/renovate/README.md
- charts/renovate/README.md.gotmpl
- charts/renovate/templates/_helpers.tpl
- charts/renovate/templates/configmap.yaml
- charts/renovate/templates/cronjob.yaml
- charts/renovate/templates/secret.yaml
- charts/renovate/values.yaml
* Allow use of existing secret - defined outside of the helm values.yaml
* Provide example renovate.config value
* Use _helper defined serviceaccountname
* Use nindent to improve readability and the existing _helper defined labels
> Allow existing secret

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Hey 👋 ,
I need to be able to use my own custom Renovate image (Mostly for injecting a `.nprmc`). A great way to do this would be to be able to use my own image, from my private registry.
To do this, I need to inject an `imagePullSecrets` into the spec of the cronjob. This PR resolves this.
How should I test my changes?
Thanks!
> feat: Add support for private custom image

- renovate.json
I traced it back to the fact that it's `helm-docs` that does the updating of the banner.  This faulted when Git reported back an exit code of 1.
Not sure that this works at all, but I attempted at something. 😄
> fix: second attempt at regex solution

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Add `backoffLimit` to Cronjob jobTemplate and a configurable value option.
Relevant Kubernetes documentation: https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
> feat: add backoffLimit to job spec

- .github/workflows/ci.yaml
Skip install chart job for local pr ( pull request source is local repo), so we don't run that expensive  job twice for maintainer / renovate pr's
> ci: skip install job on local pr

- .github/kubeval.sh
The original repository hasn't been updated in over a year. This new fork has the most stars, and is kept up-to-date with more recent k8s versions.
> ci: use up-to-date k8s schema

- README.md
- Use one sentence per line
- End sentences with a full stop
- Reduce capitalization of **Note:** message
- Add Kubernetes version support info
- Run the latest version of Prettier on the file
I think we should at least put the version support info in the README of this repository. 😉
> docs(readme): use one sentence per line, add kubernetes version support info

- charts/renovate/README.md
- charts/renovate/README.md.gotmpl
- charts/renovate/ci/ci-with-dind-values.yaml
- charts/renovate/templates/_helpers.tpl
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Hi, this PR closes #91
There are some new features via helm values:
enable dind container
change the used dind docker image
This will allow the user to enable the `binarySource=docker` option.
> feat: add dind sidecar option

- .github/helm-docs.sh
- .github/kubeval.sh
- .gitignore
- charts/renovate/templates/cronjob.yaml
closes #143 
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
> fix: use `batch/v1` api version if available

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
- Allow api version override
- Simply api version check
- Add some docs
closes #145
> feat: allow api version override

- charts/renovate/Chart.yaml
- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/templates/extra-configmap.yaml
- charts/renovate/values.yaml
Hi, this PR closes https://github.com/renovatebot/helm-charts/issues/120 
There are some new features via helm values: 
- add extra(additional) configmaps
- add extra volumes
- add extra volumeMounts
You can combine them to provide custom files(configs) to renovate's container
> feat: allow additional volumes 

- charts/renovate/templates/cronjob.yaml
- Fixes #173
- Fixes https://github.com/renovatebot/renovate/issues/13054
- regression of #170
> fix: `RENOVATE_CONFIG_FILE` not being rendered

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
hi, there. could you please review this?
as title
we need to set `startingDeadlineSeconds` value. ref: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-job-limitations
> feat: add cronjob.startingDeadlineSeconds optional value

- charts/renovate/templates/configmap.yaml
- charts/renovate/templates/cronjob.yaml
High complexity `if or` make easy to forget to add new conditions to the list, which can easily hide typos. This PR simply removes the ifs, causing `env` and `envFrom` to be rendered inconditionally.
As a downside, in some cases, this can result in empty keys, like `envFrom` below:
```yaml
containers:
- name: renovate
image: "renovate/renovate:30.2.1"
imagePullPolicy: IfNotPresent
envFrom:
resources:
{}
```
This, however, is legal yaml and applies fine on my clusters. Moreover, the chart is already doing this, by including empty strings without `| quote`:
```
spec:
backoffLimit:
template:
metadata:
```
If for some reason this is not wanted, an alternative approach could be to extract the env generation to a template:
```gotpl
{{- define "renovate.cronjob.env" -}}
{{- if …
```
> feat: remove if clauses wrapping env and envFrom

- renovate.json
Drop leading `v` on version extraction
ref:
- #179
- #183 
- 265c30069ba6f6663197f163c434f450e0fe4947
> chore: fix helm-docs version extraction

- .devcontainer/Dockerfile
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .vscode/tasks.json
Kubernetes 1.20.x is the oldest version supported across the major cloud providers.
Also updates some actions used in ci that were not correctly identified by Renovate (Needs further investigation).
- Closes #209
- Closes #178
> chore: update k8s test matrix

- charts/renovate/README.md
- charts/renovate/values.yaml
The template already supports adding pod-level securityContext options but it's currently not documented in the values file
> docs: document securityContext values option

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
This pull requests attempt to add support for initContainers. A brief example on how one would look like. This could be useful, for example, for determining a github app token just before renovate executes.
> feat: add initContainers support

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Hi,
I created this PR to integrate the possibility to set the SecurityContext on Container Level. Fix for #202
This is needed, for example, to set capabilities.  
I also changed the resource statement a bit to have the CronJob yaml clean when resources are not set.
- closes #202
Signed-off-by: dschunack <dschunack@web.de>
> Add Security Context and remove resource block if not set #202

- charts/renovate/templates/cronjob.yaml
The `activeDeadlineSeconds` value can be set from this pull-request https://github.com/renovatebot/helm-charts/pull/249, but `600` is applied by [default](https://github.com/renovatebot/helm-charts/blob/9f47b812620a77b27a90cbe0caf3f33503e75fb4/charts/renovate/templates/cronjob.yaml#L44). This is a breaking change and, it should be applied when chart users need it. And, if configuring the default value, I think `600` is too short. Anyway, it should be optional.
> fix: activeDeadlineSeconds to optional

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
I've created a fix for Github app token renewal as mentioned here #248. 
My use case is the following.
- Create an init container to handle github app token renewal and write the token into a file like so 
- `export RENOVATE_TOKEN=xxxxxx`
- The file containing the RENOVATE_TOKEN export is written to a common volume of type emptyDir that  is mounted on the same path on both the init container and the main container i.e. `/common`
The following configuration in the values file will inject an argument(s) before renovate runs within the main container. 
```
preCommand: | 
source /common/renovate.env
```
In this usecase exporting the RENOVATE_TOKEN to provide renovate the ability to authenticate with the appropriate Github repositories where the Custom Github application is installed.
Note …
> add preCommand value to cronjob template

- charts/renovate/README.md
- charts/renovate/README.md.gotmpl
- charts/renovate/templates/configmap.yaml
- charts/renovate/values.yaml
We use [helm secrets](https://github.com/jkroepke/helm-secrets) to encrypt configuration values like credentials. To reference these it would be nice to be able to reference these in the configuration without creating a custom configmap. To allow for this the tpl function has been added in this PR.
> feat: added tpl to enable templated config values

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Closes #244
As described in the issue, none of the major cloud providers supports k8s 1.20 anymore, therefore I think it's no longer necessary to support 1.20. That's why I also removed 1.20 from the workflow check in this PR
> Added support for ttlSecondsAfterFinished on the job spec

- charts/renovate/README.md
- charts/renovate/values.yaml
Closes #160
Checked all the missing values using my IDE (which were `nameOverride`, `fullnameOverride`, `nodeSelector`, `affinity`, and `tolerations`. Also documented all values that were already in `values.yaml` but had no documentation comment associated with them.
I saw no activity on #242 so decided to start over myself
> docs: Document all config values

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
When running renovatebot self-hosted using Githup App credentials, we currently have to manually approve each PR despite our auto merge and label settings. Our CI system applies the label `needs-ok-to-test` to any PR created by users outside our Github org. We need the ability to run an arbitrary sidecar container so that we can use the gh cli in a postStop hook. I'm sure other folks have use-cases for other sidecars such as cloudsql or manually-defined istio. for example:
```yaml
postCommand: |
curl -s -L --retry 5 \
https://github.com/cli/cli/releases/download/v2.23.0/gh_2.23.0_linux_amd64.tar.gz \
| tar zxvf - -C /usr/local/bin \
gh_2.23.0_linux_amd64/bin/gh \
--strip-components=2 
chmod +x /usr/local/bin/gh
gh search prs --state=open \
--label 'renovatebot' \
--label 'updatebot' \ …
```
> feat: ability to run arbitrary postCommand and sidecar extraContainers

- .github/workflows/ci.yaml
Already created PR to remove k8s 1.21 checks for when GKE and EKS 1.21 versions are EOL. 
These are the EOL dates for the EKS, GKE and, AKS 1.21:
| Provider (1.21) | EOL date            |
|---------------|-----------------|
| EKS                  | 2023-02-15       |
| GKE                 | 2023-01-31        |
| AKS                 | 2022-07-31        |
Sources:
- [EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)
- [GKE](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule-for-release-channels)
- [AKS](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)
> ci: Removed k8s 1.21 checks

- .github/kubeval.sh
- charts/renovate/README.md
- charts/renovate/ci/ci-slim-without-dind.yaml
- charts/renovate/templates/_helpers.tpl
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
- closes #281
* allow `slim.enabled: true` to allow slim images without dind, defaults to `false`
* updated readme
* add `ci/ci-slim-without-dind.yaml` test values
* update `.github/kubeval.sh` to test all k8s versions with all test values files
* set `RENOVATE_BINARY_SOURCE` env to `install` if new slim switch is enabled
> allow slim config without dind

- .devcontainer/Dockerfile
Release not available.
Reverts renovatebot/helm-charts#294
> fix: Revert "chore(deps): update dependency docker to v20.10.25"

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Starting with kubernetes 1.27 CornJobs support setting a timeZone to be used with the cron expression.
This PR allows setting this timeZone optionally.
See: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones
> feat: allow setting timeZone for CronJob Schedule

- .devcontainer/Dockerfile
- .github/workflows/ci.yaml
- README.md
A couple other fixes related to versions:
- Renovate `packageName` for `kubectl`
- Add endoflife.date links to the README
- Bump `kindest` tags
Closes #296
> ci: stop testing on k8s v1.22 and v1.23

- .devcontainer/Dockerfile
- .github/workflows/ci.yaml
Reverts renovatebot/helm-charts#317
- https://github.com/helm/chart-testing/issues/577
> fix: Revert "chore(deps): update dependency chart-testing to v3.9.0"

- .github/ct.yaml
The new CT added forwarding of this flag to Helm which in turn does not have this flag.   
As CT only runs on chart changes and not Github Actions ones, the CI checks for the upgrade have been successful.
After CT upgrade: https://github.com/renovatebot/helm-charts/actions/runs/6712778910/job/18243044331?pr=653#step:6:46
Before CT upgrade: https://github.com/renovatebot/helm-charts/actions/runs/6697045682/job/18196081288#step:6:56
We can re add this when this PR is merged https://github.com/helm/chart-testing/pull/605
> ci(ct): remove unsupported flag

- charts/renovate/templates/cronjob.yaml
Current variable for container's volume mounts condition is invalid.
`extraVolumes` is used for `spec.volumes` and `extraVolumeMounts` should be used for `spec.containers[0].volumeMounts`.
> fix: Change variable for `volumeMounts` to the correct one

- charts/renovate/templates/cronjob.yaml
Cache volumeMount was outside of the if-statement, thus it could be added without the `volumeMounts:` key existing
> fix:  cache volumeMount

- charts/renovate/values.yaml
The Chart won't render without the extra whitespaces (when using envFrom). See also https://github.com/renovatebot/helm-charts/blob/main/charts/renovate/ci/ci-values.yaml#L3
> fix: wrong identation for example

- charts/renovate/README.md
- charts/renovate/README.md.gotmpl
v16 doesn't seem relevant to me anymore, as users upgrading from pre-v16 likely have some other breaking changes to take care of. Starting anew instead of upgrading is probably easier, due to the (great!!!) effort put in to keep this Helm Chart simple.
> docs: Remove v16 upgrade notes

- charts/renovate/README.md
- charts/renovate/ci/ci-with-parallelism.yaml
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
Introduce new configurable options for defining the number of successful completions needed before marking a job complete and specifying the number of pods to run in parallel. This change enhances flexibility in managing cronjobs efficiently.
> feat: Add cronjob completions and parallelism options

- charts/renovate/templates/cronjob.yaml
The templated `preCommand` and `postCommand` values should be preceded with `set -e`, so that the Renovate Kubernetes CronJob fails directly on every non-zero exit code.
> fix: Precede preCommand and postCommand with `set -e`

- charts/renovate/README.md
- charts/renovate/templates/pvc.yaml
- charts/renovate/values.yaml
In order to support statically provisioned volumes, we add the option to render volumeName in the pvc's spec if volumeName is provided.
Defined here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#persistentvolumeclaimspec-v1-core
> feat(chart): Enable binding the cache PVC to exiting volumes

- charts/renovate/README.md
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
The [documentation](https://docs.renovatebot.com/getting-started/running/#the-full-image) points users to the 'full' image. This image is useful when users are behind restrictive firewalls. However, the chart currently requires users to override the tag to use the full image. This prevents users from upgrading the image when the chart upgrades.
This PR provides the ability for users to upgrade the image as and when chart is upgraded while also using the full image
> feat: add an opinion to use `full` tag

- .github/workflows/ci.yaml
- #579
leaving kubeval tests, as they only need ~10s
> ci: update kubernetes versions

- charts/renovate/templates/cronjob.yaml
minor changes to fix indentation and remove extra whitespace
`helm template --values=values-test.yaml --namespace renovate renovate .`
before and after:
> fix: cronjob indentation and whitespace

- charts/renovate/templates/pvc.yaml
Fix for https://github.com/renovatebot/helm-charts/pull/1593
The value field reference is non-existing, leading to:
```
Error: template: renovate/charts/renovate/templates/pvc.yaml:8:18: executing "renovate/charts/renovate/templates/pvc.yaml" at <.Values.persistence.cache.labels>: nil pointer evaluating interface {}.cache
```
> fix: persistance labels template

- charts/renovate/templates/cronjob.yaml
If a `securityContext` is defined in the chart values and `persistence.cache` is enabled, the indentation of the `securityContext` was not correct.
> fix: Adds missing indentation for securityContext

- charts/renovate/README.md
- charts/renovate/README.md.gotmpl
- charts/renovate/values.yaml
The disk cache is very likely to pile up quickly. This will
prevent the Job to be executed once the PersistentVolume is full.
More information can be found here:
renovatebot/renovate#30525
Signed-off-by: Tim Beermann <tibeer@outlook.de>
> docs: recommend redis when users want to use a cache for renovate

- charts/renovate/Chart.yaml
- charts/renovate/README.md
- charts/renovate/templates/config.yaml
- charts/renovate/templates/secret.yaml
- charts/renovate/templates/ssh-secret.yaml
- charts/renovate/values.yaml
Allow adding annotations to secret resources.
E.g.: A Kubernetes mutating webhook that makes direct secret injection using annotations - https://bank-vaults.dev/docs/mutating-webhook/annotations/
> feat(helm): Add secret annotations

- charts/renovate/templates/config.yaml
- charts/renovate/templates/cronjob.yaml
- charts/renovate/templates/extra-configmap.yaml
- charts/renovate/templates/pvc.yaml
- charts/renovate/templates/secret.yaml
- charts/renovate/templates/serviceaccount.yaml
- charts/renovate/templates/ssh-secret.yaml
It's common for helm charts to render the manifests with a namespace
matching the helm release namespace.
> feat: Add release namespace to resources

- charts/renovate/templates/extra-configmap.yaml
Fix error
```
Error: template: renovate/templates/extra-configmap.yaml:7:24: executing "renovate/templates/extra-configmap.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace Use --debug flag to render out invalid YAML
```
Related to
- https://github.com/renovatebot/helm-charts/pull/2410
> fix: nil pointer error in extra-configmap.yaml

- charts/renovate/README.md
- charts/renovate/templates/config.yaml
- charts/renovate/templates/cronjob.yaml
- charts/renovate/values.yaml
When using a json5 file formatting for the `renovate.config` key the following warning is printed on the beginning of each renovate run.
```
WARN: File contents are invalid JSON but parse using JSON5. Support for this will be removed in a future release so please change to a support .json5 file name or ensure correct JSON syntax.
```
This PR adds a new `configIsJson5` option that changes the config file extension to `.json5` to prevent this warning. It's similar to the already existing `configIsJavaScript` option.
> fix: Allow to use json5 config file without warning

- charts/renovate/Chart.yaml
- charts/renovate/README.md
- renovate.json
- let renovate bump the chart version with `bumpVersions`
- do no longer keep app version and chart version in sync
- closes #54
> feat: split chart version from renovate version

- .github/workflows/release.yaml
the default pages workflow doesn't use pinned action versions, so it's blocked from running
- fixes #3101
> ci: manually deploy pages
