charts/renovate/templates/secret.yaml

Resolve issue https://github.com/renovatebot/helm-charts/issues/62 with inline secret data

Secret data should be indent not nindent

---

charts/renovate/README.md
charts/renovate/templates/serviceaccount.yaml
charts/renovate/values.yaml

Resolves https://github.com/renovatebot/helm-charts/issues/65

Add missing serviceaccount template and set default to not enabled

---

charts/renovate/ci/ci-values.yaml

test: more realistic ci-values

---

.github/workflows/ci.yaml
renovate.json

* use shared renovate preset
* fix action versions
* run tests on all pr changes ( to validate workflow )

chore: fix renovate and ci

---

.github/helm-docs.sh
charts/renovate/README.md
charts/renovate/README.md.gotmpl
renovate.json

Also update our template, to more closely match the default template.

docs: update helm-docs version and related docs

---

renovate.json

Tries to solve the current autoupdate of the chart.

fix: remove regex that don't match

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/tools/chart-testing.sh
.devcontainer/tools/helm-docs.sh
.devcontainer/tools/kind.sh
.devcontainer/tools/kubectl.sh
.devcontainer/tools/kubeval.sh
.vscode/extensions.json
.vscode/tasks.json
renovate.json

Builds on much of the work done by @viceice for creating dependency toolchain docker images and extends this to install development toolchains as well. This is a draft PR, because I want to get feedback on the approach, before going any further.
Closes #75

chore: initial github codespace configuration

---

.editorconfig
.github/workflows/ci.yaml
.prettierrc
charts/renovate/Chart.yaml
charts/renovate/README.md
charts/renovate/values.yaml
renovate.json

Moved renovate chart on artifacthub.io to new org https://artifacthub.io/packages/helm/renovate/renovate
Maybe we can /should add some metadata? (eg using `artifacthub.io/links` to nicely name links)
https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations

feat: update chart

---

.devcontainer/Dockerfile
.devcontainer/tools/chart-testing.sh
.devcontainer/tools/helm-docs.sh
.devcontainer/tools/kind.sh
.devcontainer/tools/kubectl.sh
.devcontainer/tools/kubeval.sh
.github/helm-docs.sh
.github/kubeval.sh
.github/workflows/ci.yaml

refactor: migrate to new buildpack

---

.github/workflows/ci.yaml

Only skip install for renovate branches, as the push only runs on renovate branches

ci: only skip renovate branches

---

.github/workflows/ci.yaml
renovate.json

ci: drop kubernetes versions below 1.18

---

charts/renovate/README.md
charts/renovate/values.yaml

fix: redis password auth

---

charts/renovate/templates/cronjob.yaml

see https://github.com/renovatebot/renovate/releases/tag/30.0.0
- closes #167

fix: explicit config filename

---

charts/renovate/README.md
charts/renovate/templates/cronjob.yaml
charts/renovate/values.yaml

Rather than uninstalling, I‘d like to have the option to suspend the cronjob.

feat: add cronjob.suspend to values

---

.github/workflows/ci.yaml

Add tests for kubernetes v1.22 and 1.23.

ci: update kubernetes test matrix

---

charts/renovate/README.md
charts/renovate/templates/cronjob.yaml
charts/renovate/values.yaml

Hi,
I added the `envList` option to set env from other than the `value` source

feat: add envList option

---

.github/workflows/ci.yaml

ci: Added checks for 1.25 & 1.26 and removed checks for 1.20

---

charts/renovate/README.md
charts/renovate/README.md.gotmpl
charts/renovate/templates/cronjob.yaml
charts/renovate/templates/pvc.yaml
charts/renovate/values.yaml

Closes #163
This will only work if users don't override their baseDir/cacheDir.

Added support for Persistent Volume Claims for renovate cache

---

charts/renovate/README.md
charts/renovate/README.md.gotmpl
charts/renovate/templates/cronjob.yaml
charts/renovate/templates/pvc.yaml
charts/renovate/values.yaml

@viceice I messed up in my previous PR. This should fix it. ~My previous PR was not running the checks correctly, caused by some Github service interruption~ Not sure why it's not running the checks...
Edit: probably https://www.githubstatus.com/incidents/f3kthhhjt9ss
Edit: incident has been resolved. Added extra documentation and thereby triggered PR checks

fix: cache persistence

---

charts/renovate/templates/NOTES.txt

Updates helm notes to reflect reality.

fix: Helm does clean up kubernetes cronjobs.

---

.devcontainer/Dockerfile

- depends on https://github.com/renovatebot/.github/pull/45

chore(devcontainer): unpin docker image

---

.github/workflows/ci.yaml

- add kubernetes v1.27 to test matrix
- update json schema versions

ci: test kubernetes v1.27

---

.github/ct.yaml
.github/kubeval.sh
.github/workflows/release.yaml
README.md
charts/renovate/Chart.lock
charts/renovate/Chart.yaml

This way we don't need the manual repo adding

feat: use binami oci chart

---

.github/workflows/ci.yaml

**TODO**
- make `test-success` mandatory
- enable merge queue

ci: add success job and enable merge queue

---

renovate.json

alternatively i can copy the preset to `renovatebot/.github` repo

chore(renovate): use merge-queue preset

---

charts/renovate/Chart.yaml
renovate.json

chore(renovate): fix config

---

.devcontainer/Dockerfile
.github/helm-docs.sh

Reverts renovatebot/helm-charts#549

fix: Revert "chore(deps): update dependency helm-docs to v1.11.2"

---

.github/workflows/ci.yaml

k8s 1.28 is going to be/has been released to the major cloud providers this month

ci: Add k8s 1.28

---

renovate.json

https://github.com/helm/helm/issues/12463

chore(renovate): pin helm version

---

.github/ct.yaml

Reverses: https://github.com/renovatebot/helm-charts/pull/657

ci(ct): readd helm timeout

---

.github/helm-docs.sh
charts/renovate/README.md
charts/renovate/README.md.gotmpl

docs: check for errors

---

charts/renovate/README.md
charts/renovate/templates/cronjob.yaml
charts/renovate/values.yaml

feat: Pin CronJob to API version batch/v1

---

charts/renovate/Chart.lock
charts/renovate/Chart.yaml
charts/renovate/README.md
charts/renovate/templates/cronjob.yaml
charts/renovate/values.yaml

Closes: https://github.com/renovatebot/helm-charts/issues/1701

feat: add bitnami/common with compatibility.openshift.adaptSecurityContext

---

.github/workflows/release.yaml

Can't really test it, we need to merge and see.
- closes #2933
- https://github.com/helm/chart-releaser/issues/183#issuecomment-1189898568

feat: publish oci chart

---

renovate.json

only last multiple match string wins

chore(renovate): fix readme version bump
